name: chap_01_intro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

#이미지 가져오는
flutter:
  uses-material-design: true
  assets:
    - assets/

#변경사항 있을 시 pub get 반드시 !